---
#    - name: PAKET KURULUMLARI
#      apt:
#        name: "{{ packages }}"
#        state: latest
#        update_cache: yes
#      vars:
#        packages:
#        - lvm2
#        - ntp
#        - tcpdump
#        - wget
#        - openssl

#    - name: PAKET KURULUMLARI (Python, Ansible, Docker)
#      apt:
#        name: "{{ packages }}"
#        state: present
#        update_cache: yes
#      vars:
#        packages:
#        - python3.8
#        - docker.io

#    - name: DOCKER CE BASLAT
#      service:
#        name: docker
#        state: started
#        enabled: yes

#    - name: PIP3 YUKSELTMESI
#      shell: "python3.8 -m pip install pip --upgrade"

    - name: PIP PAKET KURULUMLARI
      pip:
        name: "{{ packages }}"
        executable: /usr/local/bin/pip3.8
      vars:
        packages:
        - boto
        - boto3
        - docker-compose
