---
- name: SWARM AGINA WORKER EKLE
  shell: "docker swarm join --token {{ hostvars[groups['manager'][0]]['manager_token']['stdout'] }} {{ hostvars[groups['manager'][0]]['ansible_default_ipv4']['address'] }}:2377"
  #when: swarm_status.rc != 0
  ignore_errors: true
  tags: swarm
