---
    - name: DOCKER PERMISSION
      shell: "sudo chmod -R 777 /var/run/docker.sock"

    - name: DOCKER KULLANICI IZNI
      shell: "sudo usermod -aG docker $USER"

    - name: HELLO WORLD
      shell: "docker run hello-world"
      ignore_errors: true
