---
#    - name: DOCKER GROUP ADD
#      shell: "sudo groupadd docker"

    - name: DOCKER KULLANICI IZNI
      shell: "sudo usermod -aG docker $USER"

#    - name: NEWGRP DOCKER
#      shell: "sudo newgrp docker"

#    - name: HELLO WORLD
#      shell: "docker run hello-world"
#      ignore_errors: true